### ISSUE TITLE
Workshop not configured

### ISSUE THREAD

**Issue by mdozmorov** [montilab/hypeR-workshop#1]
@anfederico, your workshop does not use GitHub Actions, as described in the workshop template https://github.com/seandavi/BuildABiocWorkshop2020. It is incompatible with the cloud setup to run workshops. Please, check.

**Comment by anfederico** [comment]
@mdozmorov Will have a fix in soon.

**Comment by lwaldron** [comment]
The critical issue currently is that when you open an RStudio instance on this image, you don't see anything. Also you can't build the vignette. Here are some things you can do to test:

Run rcmdcheck as done in GH Actions (can change error_on to "error" if you are OK with warnings):
```
docker run -it montilab/hyperworkshop:latest R -e 'rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning", check_dir = "check")'
```

Open in RStudio, and you don't see any files (although `library(hyperworkshop)` works):
```
docker run -e DISABLE_AUTH=TRUE -p 8787:8787 montilab/hyperworkshop:latest
```

**Comment by mdozmorov** [comment]
@anfederico, any progress on this?

**Comment by anfederico** [comment]
Fixed

https://github.com/montilab/hypeR-workshop/runs/916909571

Note: I ignored warnings when checking because the vignette needs some images in the vignette folder for pckgdown to render properly when on Github Pages.

```
docker run -it montilab/hyperworkshop:latest R -e 'rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "error", check_dir = "check")'
```

**Comment by mdozmorov** [comment]
Yes, it now loads in the cloud, http://workshop.bioc.cancerdatasci.org/. And yes, the vignette needs to be polished. I used an external image for the vignette, here’s how if this may help https://github.com/mdozmorov/HiCcompareWorkshop/tree/master/vignettes

**Comment by mdozmorov** [comment]
Closing, not necessary at the moment
